### PR TITLE
Add  the translation (including dictionary)

### PR DESCRIPTION
**Pull request by CHA2172886**
Add  the translation_Chinese (including dictionary), support All Theme

### CODE REVIEW

**Comment by CHA2172886** [comment]
dictionary including 70% sdk assembly translation, and then easy to add more

**Comment by myo** [comment]
hi thanks for your PR and sorry for your wait time, have you tested that everything works fine?

**Comment by myo** [comment]
alright everything seems to work fine. thanks and please leave your forum username :P

**Comment by CHA2172886** [comment]
username: NightMoon

**Pull request merged**
